### PR TITLE
Show skipped tests details with same format than error tests details

### PR DESCRIPTION
**Pull request by aiKrice**
Hello Orta, thanks for this beautiful tools which is Danger.
I add a parameter for skipped tests and give possibilty to have more details for skipped tests.

### CODE REVIEW

**Comment by orta** [comment]
Cool, looks good, it will need a README change so others know it exists and then this is good to go 👍

**Comment by aiKrice** [comment]
Done

**Comment by aiKrice** [comment]
Hi buddy @orta . As soon as you can find some minutes, dont forget it ;). Cheers

**Comment by orta** [comment]
Sorry, too many notifications - looks good

**Comment by orta** [comment]
Alright, that's shipped as 1.0.1

**Comment by orta** [comment]
We got an issue with this PR: https://github.com/orta/danger-junit/issues/27

**Pull request merged**
